name: CI-Build

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17

    - name: Install and start SFTP
      run: |
        # Install SSH server in Ubuntu
        sudo apt install openssh-server
        # Enable the ssh service
        sudo systemctl enable ssh
        # Start the ssh service
        sudo systemctl start ssh

    - name: Create a test user account
      run: sudo useradd -s /bin/bash -d /home/usr -m -g ssh -p $(echo pwd | openssl passwd -1 -stdin) usr

    - name: Build with Maven
      run: mvn clean verify --batch-mode

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "*/target/*-reports/TEST*.xml"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          */target/*.iar
          *product/target/*.zip
