name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:
  workflow_call:
    inputs:
      mvnArgs:
        type: string
        required: false
      ivyVersion:
        type: string
        default: dev
        description: the ivy version to use (e.g. dev/nightly/nightly-10/...)
      ivyPluginVersion:
        type: string
        default: 11.4.0-SNAPSHOT
      testerVersion:
        type: string
        default: 11.4.0-SNAPSHOT

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      mvnArgs: '"-Divy.engine.download.url=https://dev.axonivy.com/permalink/dev/axonivy-engine.zip" "-Divy.engine.version=(10.0.0,]"'
      javaVersion: 21
      mvnVersion: 3.9.8
